replicaCount: 3
image:
  repository: anksa/nodejs-webapp
  tag: v2
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  protocal: HTTPS
  port: 443
  externalTrafficPolicy: Cluster
persistence:
  enabled: true
  storageClass: standard
  accessMode: ReadWriteOnce
  size: 1Gi
secrets:
  tlsSecret: webapp-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  hosts:
    - host: webapp.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: webapp-secret
     hosts:
       - webapp.example.com